### ISSUE TITLE
Make Wagmi storage configurable (useful for web3:// + EVM Browser)

### ISSUE THREAD

**Issue by nand2** [visualizevalue/mint#14]
Hi!

Would it be possible to make the Wagmi storage option configurable?

At the moment, in 2.wagmi.ts, Wagmi is configured with
```js
    storage: createStorage({
      storage: cookieStorage,
    }),
```
I would like to override this config with : 
```js
    storage: window.location.protocol === 'web3:' ? null : createStorage({
      storage: cookieStorage,
    }),
```

Conceptually this would not be needed -- the `web3://` protocol supports cookies and localStorage.
But at current development stage, the only native `web3:// native browser [EVM Browser](https://github.com/web3-protocol/evm-browser), has some features disabled (cookies, localStorage, cf https://github.com/web3-protocol/evm-browser/issues/3 ) due to restrictions by electron.

(This + the use of the `/#/` routing (for which you gave me configuration indications) are the two things I had to make to make `web3://ocweb.eth` work in EVM Browser)

Thanks for reviewing this!

**Comment by jwahdatehagh** [comment]
will look into it! also have an interest in making configuring RPCs a runtime option (e.g. adjust in settings).

one potential issue here is that it should also work in a node js (server) context where there is no `window` available.

**Comment by nand2** [comment]
It would be good for my case even if the setting is static 🫡 (I would set it to null, so no wagmi storage for all cases) 
Thanks!

**Comment by nand2** [comment]
I close the issue : 
There are in fact many more things using cookies/localstorage, and too difficult to make configurable ; so I will not request this anymore  :-)
